version: "3.8"

services:
  sample:
    build: .
    image: sample-runner
    container_name: sample-runner
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    stdin_open: true
    tty: true
    command: sh ./sample.sh